ALTER TABLE voters ADD vote_Ppresident VARCHAR(100) DEFAULT NULL;
ALTER TABLE voters ADD vote_treasurer VARCHAR(100) DEFAULT NULL;
ALTER TABLE voters ADD vote_fin_secretary VARCHAR(100) DEFAULT NULL;
ALTER TABLE voters ADD vote_pro VARCHAR(100) DEFAULT NULL;
-- ALTER TABLE voters ADD vote_Ppresident VARCHAR(100) DEFAULT NULL
